Tp4/Tp7.MVC/Models/TableViewModel/ShipperView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tp7.MVC.Models.TableViewModel
{
    public class ShipperView
    {
        public int ShipperID { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
    }
}

Tp4/Tp7.MVC/Controllers/ShipperController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tp4.Entities;
using Tp4.Logic;
using Tp7.MVC.Models.FormViewModel;
using Tp7.MVC.Models.TableViewModel;

namespace Tp7.MVC.Controllers
{
    public class ShipperController : Controller
    {
        [HttpGet]
        public ActionResult Index(string message)
        {
            ViewBag.ErrorMessage = message;
            List<ShipperView> shippers = new List<ShipperView>();
            try
            {
                ShippersLogic shippersLogic = new ShippersLogic();
                shippers = shippersLogic.GetAll().Select(
                    s => new ShipperView
                    {
                        ShipperID = s.ShipperID,
                        CompanyName = s.CompanyName,
                        Phone = s.Phone
                    }).ToList();
                return View(shippers);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage += " - " + e.Message;
                return View(shippers);
            }
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(ShipperFormModel form)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ShippersLogic shippersLogic = new ShippersLogic();
                    int nuevoId = shippersLogic.FindLastIndex() + 1;
                    shippersLogic.Add(new Shippers
                    {
                        CompanyName = form.CompanyName,
                        Phone = form.Phone,
                        ShipperID = nuevoId
                    });
                    return RedirectToAction("Index");
                }
                catch (InvalidOperationException i)
                {
                    ViewBag.ErrorMessage = i.Message;
                    return View(form);
                }
                catch (ArgumentNullException a)
                {
                    ViewBag.ErrorMessage = a.Message;
                    return View(form);
                }
                catch (DbEntityValidationException db)
                {
                    ViewBag.ErrorMessage = GetErrorMessageDataBase(db);
                    return View(form);
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    return View(form);
                }
            }
            else
            {
                return View(form);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            try
            {
                ShippersLogic shippersLogic = new ShippersLogic();
                var find = shippersLogic.FindOne(id);
                if (find != null)
                {
                    ShipperFormModel form = new ShipperFormModel
                    {
                        ShipperID = find.ShipperID,
                        CompanyName = find.CompanyName,
                        Phone = find.Phone
                    };
                    return View(form);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Edit(ShipperFormModel form)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ShippersLogic shippersLogic = new ShippersLogic();
                    var find = shippersLogic.FindOne((int)form.ShipperID);
                    if (find != null)
                    {
                        shippersLogic.Update(new Shippers
                        {
                            ShipperID = (int)form.ShipperID,
                            CompanyName = form.CompanyName,
                            Phone = form.Phone
                        });
                        ViewBag.Message = "Se ha editado con exito";
                        return View(form);
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
                catch (DbEntityValidationException db)
                {
                    ViewBag.ErrorMessage = GetErrorMessageDataBase(db);
                    return View(form);
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    return View(form);
                }
            }
            else
            {
                return View(form);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                ShippersLogic shippersLogic = new ShippersLogic();
                if (shippersLogic.Exist(id))
                {
                    shippersLogic.Delete(id);
                    return Content("1");
                }
                else
                {
                    return Content("0");
                }
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }
        }

        [HttpGet]
        public ActionResult CreateOrEdit(int? id)
        {
            if (string.IsNullOrWhiteSpace(id.ToString()))
            {
                ViewBag.Action = "Agregar Expedidor";
                return View();
            }
            else
            {
                try
                {
                    ShippersLogic shippersLogic = new ShippersLogic();
                    var find = shippersLogic.FindOne((int)id);
                    if (find != null)
                    {
                        ShipperFormModel form = new ShipperFormModel
                        {
                            ShipperID = find.ShipperID,
                            CompanyName = find.CompanyName,
                            Phone = find.Phone
                        };
                        ViewBag.Action = "Editar Expedidor";
                        return View(form);
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    return RedirectToAction("Index", new { message = e.Message });
                }
            }
        }


        [HttpPost]
        public ActionResult CreateOrEdit(ShipperFormModel form)
        {
            if (form.ShipperID != null)
            {
                ViewBag.Action = "Editar Expedidor";
                if (ModelState.IsValid)
                {
                    try
                    {
                        ShippersLogic shippersLogic = new ShippersLogic();
                        var find = shippersLogic.FindOne((int)form.ShipperID);
                        if (find != null)
                        {
                            shippersLogic.Update(new Shippers
                            {
                                ShipperID = (int)form.ShipperID,
                                CompanyName = form.CompanyName,
                                Phone = form.Phone
                            });
                            ViewBag.Message = "Se ha editado con exito";
                            return View(form);
                        }
                        else
                        {
                            return RedirectToAction("Index", new { message= "No se encontro el expedidor"});
                        }
                    }
                    catch (DbEntityValidationException db)
                    {
                        ViewBag.ErrorMessage = GetErrorMessageDataBase(db);
                        return View(form);
                    }
                    catch (Exception e)
                    {
                        ViewBag.ErrorMessage = e.Message;
                        return View(form);
                    }
                }
                else
                {
                    return View(form);
                }
            }
            else
            {
                ViewBag.Action = "Agregar Expedidor";
                if (ModelState.IsValid)
                {
                    try
                    {
                        ShippersLogic shippersLogic = new ShippersLogic();
                        int nuevoId = shippersLogic.FindLastIndex() + 1;
                        shippersLogic.Add(new Shippers
                        {
                            CompanyName = form.CompanyName,
                            Phone = form.Phone,
                            ShipperID = nuevoId
                        });
                        return RedirectToAction("Index");
                    }
                    catch (InvalidOperationException i)
                    {
                        ViewBag.ErrorMessage = i.Message;
                        return View(form);
                    }
                    catch (ArgumentNullException a)
                    {
                        ViewBag.ErrorMessage = a.Message;
                        return View(form);
                    }
                    catch (DbEntityValidationException db)
                    {
                        ViewBag.ErrorMessage = GetErrorMessageDataBase(db);
                        return View(form);
                    }
                    catch (Exception e)
                    {

Tp4/Tp7.MVC/Views/Shipper/Add.cshtml
@model Tp7.MVC.Models.FormViewModel.ShipperFormModel

@{
    ViewBag.Title = "Agregar Expedidor";
}

<h2>Crear nuevo Expedidor</h2>

@using (Html.BeginForm("Add", "Shipper", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label for="CompanyName">Nombre de Compañia<span style="color:red">*</span>:</label>
        @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", required = string.Empty, maxlength = 40, minlength = 1 } })
        @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label for="Phone">Telefono:</label>
        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", maxlength = 24 } })
        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-outline-success" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index")
</div>
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger" role="alert" style="border:1px solid red">Server Message: <br />@ViewBag.ErrorMessage</div>
}

Tp4/Tp7.MVC/Views/Shipper/CreateOrEdit.cshtml
@model Tp7.MVC.Models.FormViewModel.ShipperFormModel

@{
    ViewBag.Title = ViewBag.Action;
}

<h2>@ViewBag.Action</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @*<div class="form-group" hidden>
            @Html.LabelFor(model => model.ShipperID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShipperID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShipperID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @Html.HiddenFor(s => s.ShipperID)

    <div class="form-group">
        <label for="CompanyName">Nombre de Compañia<span style="color:red">*</span>:</label>
        @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", required = string.Empty, maxlength = 40, minlength = 1 } })
        @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="Phone">Telefono:</label>
        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", maxlength = 24 } })
        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Aceptar" class="btn btn-outline-success" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index")
</div>
@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert" style="border:1px solid green">@ViewBag.Message @Html.ActionLink("Ver listado", "Index", "Shipper")</div>
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger" role="alert" style="border:1px solid red">Server Message: <br />@ViewBag.ErrorMessage</div>
}

Tp4/Tp7.MVC/Views/Shipper/Edit.cshtml
@model Tp7.MVC.Models.FormViewModel.ShipperFormModel

@{
    ViewBag.Title = "Editar Expedidor";
}

<h2>Editar Expedidor</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" hidden>
        @Html.LabelFor(model => model.ShipperID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ShipperID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ShipperID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="CompanyName">Nombre de Compañia<span style="color:red">*</span>:</label>
        @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", required = string.Empty, maxlength = 40, minlength = 1 } })
        @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="Phone">Telefono:</label>
        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", maxlength = 24 } })
        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-outline-success" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index")
</div>
@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert" style="border:1px solid green">@ViewBag.Message @Html.ActionLink("Ver listado", "Index", "Shipper")</div>
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger" role="alert" style="border:1px solid red">Server Message: <br />@ViewBag.ErrorMessage</div>
}

Tp4/Tp7.MVC/Views/Shipper/Index.cshtml
@model List<Tp7.MVC.Models.TableViewModel.ShipperView>
@{
    ViewBag.Title = "Expedidores";
}

<h2>Lista de Expedidores</h2>

<div class="table-responsive">
    <table class="table table-bordered table-hover table-sm">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre de Compañia</th>
                <th scope="col">Teléfono</th>
                <th scope="col">Accciones</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Count > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td scope="row" class="align-middle">@item.ShipperID</td>
                        <td class="align-middle">@item.CompanyName</td>
                        <td class="align-middle">@item.Phone</td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                @Html.ActionLink("Editar", "Edit", new { id = item.ShipperID }, new { @class = "btn btn-outline-warning" })
                                @Html.ActionLink("Editar v2", "CreateOrEdit", "Shipper", new { id = item.ShipperID }, new { @class = "btn btn-outline-secondary btn-block" })
                                <button type="button" onclick="deleteShipper(@item.ShipperID)" class="btn btn-outline-danger">Eliminar</button>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4">No hay Expedidores</td>
                </tr>
            }

        </tbody>
    </table>
    @Html.ActionLink("Crear nuevo Expedidor", "Add", "Shipper", new { @class = "btn btn-primary btn-block" })
    @Html.ActionLink("Crear nuevo Expedidor v2", "CreateOrEdit", "Shipper", new { @class = "btn btn-secondary btn-block" })

</div>

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger" role="alert" style="border:1px solid red">Server Message: <br />@ViewBag.ErrorMessage</div>
}


<script>
    function deleteShipper(id) {
        if (confirm("¿Esta seguro de eliminar el expedidor?")) {
            url = "@Url.Content("~/Shipper/Delete")" + "/" + id;
            $.post(url, function (data) {
                if (data == "1") {
                    alert("Se ha eliminado el expedidor");
                    window.location.reload(true);
                } else if (data == "0") {
                    alert("No existe el expedidor");
                } else {
                    alert("Error: "+data);
                }
            }).fail(function (response) {
                alert("Hubo fallas en el sistema");
                console.log(response);
            });
        }
    }
</script>